//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy
    {
        public int buy_id { get; set; }
        public int client_id { get; set; }
        public int game_id { get; set; }
        public System.DateTime buy_date { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual games games { get; set; }
    }
}
